### ISSUE TITLE
blender 2.79 windows 10 can't import throws errors

### ISSUE THREAD

**Issue by zchana** [martijnberger/pyslapi#23]
current version from master:
only camera is imported
I've also tried to install previous version without luck

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 681, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(context, **keywords)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 157, in load
    self.write_entities(self.skp_model.entities, "Sketchup", Matrix.Identity(4))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 428, in write_entities
    etype=EntityType.group)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 428, in write_entities
    etype=EntityType.group)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 409, in write_entities
    me, alpha = self.write_mesh_data(entities=entities, name=name, default_material=default_material)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\sketchup_importer\__init__.py", line 332, in write_mesh_data
    for edge in f.edges:
AttributeError: 'sketchup.Face' object has no attribute 'edges'

location: <unknown location>:-1
```
  
windows 10 64 bit
blender 2.79

**Comment by fractalfederation** [comment]
I am using same OS and Blender version. I have the latest release, 0.18. I can import 2017 sketchup files with no issue. It's possible the latest from master has an error, did you try 0.18? 2018 sketchup files aren't supported with 0.18.
