### ISSUE TITLE
Error importing Sketchup-file

### ISSUE THREAD

**Issue by jorismeuleman** [martijnberger/pyslapi#36]
I get the following error in Blender 2.82a while importing a sketchup-file. I do not have Sketchup. The file is from a company that designed my garden.

Traceback (most recent call last):
  File "C:\Users\Joris\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 868, in execute
    context, **keywords)
  File "C:\Users\Joris\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 184, in load
    self.write_duplicateable_groups()
  File "C:\Users\Joris\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\SketchUp_Importer\__init__.py", line 237, in write_duplicateable_groups
    group = bpy.data.groups.new(name=gname)
AttributeError: 'BlendData' object has no attribute 'groups'

location: <unknown location>:-1

**Comment by Tulasinathreddy** [comment]
Check if you have added groups in your SketchUp file 

Make some objects into group and try again 

It should work !!
