### ISSUE TITLE
This problem appears when importing from SketchUp

### ISSUE THREAD

**Issue by etqa** [martijnberger/pyslapi#54]
Python: Traceback (most recent call last):
  File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchup_importer\__init__.py", line 1039, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchup_importer\__init__.py", line 276, in load
    self.write_duplicateable_groups()
  File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchup_importer\__init__.py", line 318, in write_duplicateable_groups
    component_stats = self.analyze_entities(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchup_importer\__init__.py", line 389, in analyze_entities
    cdef = self.skp_components[instance.definition.name]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\looks\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\sketchup_importer\SKPutil\__init__.py", line 29, in __getitem__
    return dict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Component199#1'

**Comment by long22262** [comment]
я хз бро

**Comment by long22262** [comment]
такая же хуйня
