### ISSUE TITLE
Importer crash with some files

### ISSUE THREAD

**Issue by mvdwetering** [martijnberger/pyslapi#6]
I have the importer crash on some Sketchup files, others work fine.I tried stripping down the file by removing as much as is possible (actually no objects seem to be left, just a few scenes and layers). When I remove the "Van Sleeuwen" layer then it seems to import.

Blender version is 2.75. Sketchup version used is Sketchup Make 2015. 
A file that has the issue https://drive.google.com/file/d/0B2PJOa1lf5nSY1JXR2l3aF93QlE/view?usp=sharing

The error I get when importing is:

```
Traceback (most recent call last):
  File "C:\Users\Michel\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 635, in execute
    return SceneImporter().set_filename(keywords['filepath']).load(context, **keywords)
  File "C:\Users\Michel\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 157, in load
    self.write_materials(self.skp_model.materials)
  File "C:\Users\Michel\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 284, in write_materials
    tex.write(tmp_name)
  File "sketchup.pyx", line 286, in sketchup.Texture.write (sketchup.cpp:5766)
  File "sketchup.pyx", line 71, in sketchup.check_result (sketchup.cpp:2466)
RuntimeError: Sketchup library giving unexpected results SU_ERROR_SERIALIZATION

location: <unknown location>:-1
```

**Comment by martijnberger** [comment]
Closing stale issue
